#!/usr/bin/env perl

my $SEND = "4254send";
my $RECV = "4254recv";
my $NETSIM = "/usr/local/bin/netsim";
my $RUN = "/usr/local/bin/nettest";
my $CGST = "/usr/local/bin/congestiontest";

if (! (-e $SEND)) {
  die("Unable to find executable '$SEND'.\n");
}

if (! (-e $RECV)) {
  die("Unable to find executable '$RECV'.\n");
}

if (! (-e $NETSIM)) {
  die("Unable to find executable '$NETSIM'.\n");
}
if (! (-e $RUN)) {
  die("Unable to find executable '$RUN'.\n");
}



# print "\nRunning Congestion Test\n";
# runCongestionTest("Large 0.1 Mb/s 50 ms latency", "--bandwidth 0.1 --latency 50", 3, "large");
# runCongestionTest("Huge 0.1 Mb/s 50 ms latency", "--bandwidth 0.1 --latency 50", 3, "huge");

# # runSim("Large 0.5 Mb/s 10 ms latency", "--bandwidth 0.5");
# runCongestionTest("", "", 2, 'huge');

# print "\nRunning Congestion Test for 3 users with CDN\n";
# runCongestionTest("Large 100 Mb/s 15 ms latency 0.001 loss 250 Mb queue", "--bandwidth 100 --latency 15 --drop 0.001 --limit 250", 3, "large");

# print "\nRunning Congestion Test for 10 users with CDN with 1% loss\n";
# runCongestionTest("Large 100 Mb/s 15 ms latency 1 loss 250 Mb queue", "--bandwidth 100 --latency 15 --drop 1 --limit 500", 10, "large");

print "\nRunning Congestion Test for 10 users with CDN with 10% loss\n";
runCongestionTest("Large 100 Mb/s 15 ms latency 1 loss 250 Mb queue", "--bandwidth 100 --latency 15 --drop 1 --limit 500", 5, "large");



sub runCongestionTest {
  my ($problem, $simargline, $numpairs, $size) = @_;

  print "\n  $problem\n";
  `$NETSIM $simargline`;

  if ($numpairs == 1) { print "  Transfer $size data between $numpairs pair\n"; }
  else { print "  Transfer $size data between $numpairs pairs\n"; }

  $output = `$CGST --size=$size --numpairs=$numpairs `;

}

sub runSim {
  my ($problem, $simargline) = @_;

  print "\n  $problem\n";
  `$NETSIM $simargline`;

}
